name: Build/Release

on:
  push:
    branches: [ develop ]
    tags:
      - 'v*.*.*'

jobs:
  release:
    runs-on: ${{matrix.os}}
    strategy:
      matrix:
        os: [windows-2016] # [windows-2016, macOS-10.14, ubuntu-18.04]

    steps:
      - name: Checks out my repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 1

      - name: Get yarn cache
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn cache dir)"

      - name: Cache dependencies
        uses: actions/cache@v1.1.2
        id: yarn-cache # use this to check for `cache-hit` (`steps.yarn-cache.outputs.cache-hit != 'true'`)
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: Install yarn dependencies
        run: |
          echo "Node.js runtime version: $(node -v)"
          yarn config set registry https://registry.npm.taobao.org
          yarn

      - name: Release Electron app
        run: |
          yarn package

      - name: Upload artifact file
        uses: actions/upload-artifact@v1
        with:
          name: ${{ matrix.os }}
          path: dist

