name: Build/Release

on:
  push:
    branches: [ develop ]
    tags:
      - 'v*.*.*'

jobs:
  release:
    runs-on: ${{matrix.os}}
    strategy:
      matrix:
        os: [windows-2019]

    steps:
      - name: Checks out my repository
        uses: actions/checkout@v2

      - name: Get yarn cache
        id: yarn-cache
        run: echo "::set-output name=dir::$(yarn cache dir)"

      - name: Cache dependencies
        uses: actions/cache@v1
        with:
          path: ${{ steps.yarn-cache.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: Install yarn dependencies
        run: |
          echo Node.js runtime version: $(node -v)
          yarn config set registry https://registry.npm.taobao.org
          yarn

      - name: Release Electron app
        run: |
          echo fs.inotify.max_user_watches=524288 | sudo tee -a /etc/sysctl.conf && sudo sysctl -p
          yarn package

      - name: Upload artifact file
        uses: actions/upload-artifact@v1
        with:
          name: electron-antd-1.0.0.exe
          path: release/electron-antd-release-1.0.0.0001

